### ISSUE TITLE
MAP-ELITES Bin Depth

### ISSUE THREAD

**Issue by mathyouf** [CarperAI/ELM#11]
We've selected a depth of just 1 for each niche (`self.bins `) in our implementation of MAP-ELITES correct (only save the best result for that niche)? 

Or is `n_bins` the depth, in which case we'd want to edit line 55 to insert the new performance if it is in the top `n_bins` fitness for that niche.

https://github.com/mathyouf/ELM/blob/main/map_elites/map_elites.py#L55

![deepgridmape](https://user-images.githubusercontent.com/19615875/194683627-a67055e1-3489-4d45-946b-50cac48978e5.jpeg)

**Comment by herbiebradley** [comment]
Yes, I think we have depth 1, since the ELM paper refers to a single inhabitant for each niche. `n_bins` should be the size of each dimension (in the current code we can't have a non-hypercube behaviour space, but we should probably change that). To generalise our implementation we could add code to handle depth > 1, as you say, but that won't be immediately used for Sodaracers.

**Comment by herbiebradley** [comment]
Closed by #16, since we now have a `history_length` dimension in MAPElites.
